// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(entityID: string): Promise<$models.Bus> & { cancel(): void } {
    let $resultPromise = $Call.ByID(920363765, entityID) as any;
    return $resultPromise;
}

export function GetInvalidNames(entityID: string): Promise<string[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4181252272, entityID) as any;
    return $resultPromise;
}

export function GetNames(): Promise<string[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1992496223) as any;
    return $resultPromise;
}

export function ListBase(): Promise<$models.BusBase[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3115506830) as any;
    return $resultPromise;
}

export function UpdateDesc(entityID: string, desc: string): Promise<$models.Bus> & { cancel(): void } {
    let $resultPromise = $Call.ByID(982331387, entityID, desc) as any;
    return $resultPromise;
}

export function UpdateName(entityID: string, name: string): Promise<$models.Bus> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3117407681, entityID, name) as any;
    return $resultPromise;
}
