// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Redo(): Promise<$models.History> & { cancel(): void } {
    let $resultPromise = $Call.ByID(912254873) as any;
    return $resultPromise;
}

export function Undo(): Promise<$models.History> & { cancel(): void } {
    let $resultPromise = $Call.ByID(877284479) as any;
    return $resultPromise;
}
