// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(): Promise<$models.Message> & { cancel(): void } {
    let $resultPromise = $Call.ByID(383147390) as any;
    return $resultPromise;
}

export function Register(busEntID: string, nodeEntID: string, msgEntID: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3283363979, busEntID, nodeEntID, msgEntID) as any;
    return $resultPromise;
}

export function SetDesc(desc: string): Promise<$models.Message> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2250476003, desc) as any;
    return $resultPromise;
}

export function UpdateName(name: string): Promise<$models.Message> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1372204560, name) as any;
    return $resultPromise;
}
