// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetNetwork(): Promise<$models.Network> & { cancel(): void } {
    let $resultPromise = $Call.ByID(742909121) as any;
    return $resultPromise;
}

export function GetNetworkStub(): Promise<$models.NetworkStub> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1431333233) as any;
    return $resultPromise;
}
