// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetMessage(busID: string, nodeID: string, msgID: string): Promise<$models.Message> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4130498616, busID, nodeID, msgID) as any;
    return $resultPromise;
}

export function GetNetwork(): Promise<$models.Network | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(742909121) as any;
    return $resultPromise;
}
