// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddBus(): Promise<$models.Network> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2479060660) as any;
    return $resultPromise;
}

export function DeleteBuses(req: $models.DeleteBusesReq): Promise<$models.Network> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1819632418, req) as any;
    return $resultPromise;
}

export function Get(): Promise<$models.Network> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1942428257) as any;
    return $resultPromise;
}

export function UpdateDesc(req: $models.UpdateDescReq): Promise<$models.Network> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3963864903, req) as any;
    return $resultPromise;
}

export function UpdateName(req: $models.UpdateNameReq): Promise<$models.Network> & { cancel(): void } {
    let $resultPromise = $Call.ByID(502949925, req) as any;
    return $resultPromise;
}
