// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AttachBus(entityID: string, interfaceNumber: number, busEntityID: string): Promise<$models.Node> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2185278590, entityID, interfaceNumber, busEntityID) as any;
    return $resultPromise;
}

export function Get(entityID: string): Promise<$models.Node> & { cancel(): void } {
    let $resultPromise = $Call.ByID(963582531, entityID) as any;
    return $resultPromise;
}

export function GetInvalidIDs(entityID: string): Promise<number[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3779751492, entityID) as any;
    return $resultPromise;
}

export function GetInvalidNames(entityID: string): Promise<string[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3477642942, entityID) as any;
    return $resultPromise;
}

export function GetNames(): Promise<string[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2126753985) as any;
    return $resultPromise;
}

export function UpdateDesc(entityID: string, desc: string): Promise<$models.Node> & { cancel(): void } {
    let $resultPromise = $Call.ByID(663236641, entityID, desc) as any;
    return $resultPromise;
}

export function UpdateID(entityID: string, id: number): Promise<$models.Node> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2627669165, entityID, id) as any;
    return $resultPromise;
}

export function UpdateName(entityID: string, name: string): Promise<$models.Node> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2144136979, entityID, name) as any;
    return $resultPromise;
}
