// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(req: $models.CreateSignalTypeReq): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2414567789, req) as any;
    return $resultPromise;
}

export function Delete(entityID: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2278708154, entityID) as any;
    return $resultPromise;
}

export function Get(entityID: string): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2443930791, entityID) as any;
    return $resultPromise;
}

export function GetInvalidNames(entityID: string): Promise<string[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1761936154, entityID) as any;
    return $resultPromise;
}

export function ListBase(): Promise<$models.BaseEntity[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(169979836) as any;
    return $resultPromise;
}

export function ListBrief(): Promise<$models.SignalTypeBrief[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4045291091) as any;
    return $resultPromise;
}

export function UpdateDesc(entityID: string, req: $models.UpdateDescReq): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3391491109, entityID, req) as any;
    return $resultPromise;
}

export function UpdateMax(entityID: string, req: $models.UpdateMaxReq): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1547565842, entityID, req) as any;
    return $resultPromise;
}

export function UpdateMin(entityID: string, req: $models.UpdateMinReq): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1177178296, entityID, req) as any;
    return $resultPromise;
}

export function UpdateName(entityID: string, req: $models.UpdateNameReq): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(470311103, entityID, req) as any;
    return $resultPromise;
}

export function UpdateOffset(entityID: string, req: $models.UpdateOffsetReq): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(226325631, entityID, req) as any;
    return $resultPromise;
}

export function UpdateScale(entityID: string, req: $models.UpdateScaleReq): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3856836030, entityID, req) as any;
    return $resultPromise;
}

export function UpdateSigned(entityID: string, req: $models.UpdateSignedReq): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4062931212, entityID, req) as any;
    return $resultPromise;
}
