// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(entityID: string): Promise<$models.Signal> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2188749399, entityID) as any;
    return $resultPromise;
}

export function GetInvalidNames(entityID: string): Promise<string[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2274257162, entityID) as any;
    return $resultPromise;
}

export function ListBase(): Promise<$models.BaseEntity[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(928281036) as any;
    return $resultPromise;
}

export function UpdateDesc(entityID: string, req: $models.UpdateDescReq): Promise<$models.Signal> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2520689557, entityID, req) as any;
    return $resultPromise;
}

export function UpdateName(entityID: string, req: $models.UpdateNameReq): Promise<$models.Signal> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2911335503, entityID, req) as any;
    return $resultPromise;
}

export function UpdateSignalType(entityID: string, req: $models.UpdateSignalTypeReq): Promise<$models.Signal> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1801780632, entityID, req) as any;
    return $resultPromise;
}

export function UpdateSignalUnit(entityID: string, req: $models.UpdateSignalUnitReq): Promise<$models.Signal> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1854190942, entityID, req) as any;
    return $resultPromise;
}
