// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(entityID: string): Promise<$models.SignalUnit> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3658353397, entityID) as any;
    return $resultPromise;
}

export function GetNames(): Promise<string[] | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2566933599) as any;
    return $resultPromise;
}
