// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(entityID: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(312713075, entityID) as any;
    return $resultPromise;
}

export function Get(entityID: string): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2443930791, entityID) as any;
    return $resultPromise;
}

export function GetOpen(entityID: string): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1647851851, entityID) as any;
    return $resultPromise;
}

export function Open(entityID: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2916965113, entityID) as any;
    return $resultPromise;
}

export function UpdateDesc(entityID: string, newDesc: string): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3391491109, entityID, newDesc) as any;
    return $resultPromise;
}

export function UpdateName(entityID: string, newName: string): Promise<$models.SignalType> & { cancel(): void } {
    let $resultPromise = $Call.ByID(470311103, entityID, newName) as any;
    return $resultPromise;
}
