// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


/**
 * SignalKind rappresents the kind of a [Signal].
 * It can be standard, enum, or multiplexer
 */
export enum SignalKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * SignalKindStandard defines a standard signal.
     */
    SignalKindStandard = 0,

    /**
     * SignalKindEnum defines a enum signal.
     */
    SignalKindEnum = 1,

    /**
     * SignalKindMultiplexer defines a multiplexer signal.
     */
    SignalKindMultiplexer = 2,
};
