// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


/**
 * CANID is the CAN-ID of a [Message] within a [Bus].
 * Every message should have a different CAN-ID.
 */
export type CANID = number;

/**
 * MessageByteOrder rappresents the byte order of the payload of a [Message].
 * By default a [MessageByteOrder] of [MessageByteOrderLittleEndian] is used.
 */
export enum MessageByteOrder {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * MessageByteOrderLittleEndian defines a little endian byte order.
     */
    MessageByteOrderLittleEndian = 0,

    /**
     * MessageByteOrderBigEndian defines a big endian byte order.
     */
    MessageByteOrderBigEndian = 1,
};

/**
 * MessageID rappresents the ID of a [Message].
 * It must be unique within all the messages sended by a [NodeInterface].
 */
export type MessageID = number;

/**
 * SignalKind rappresents the kind of a [Signal].
 * It can be standard, enum, or multiplexer
 */
export enum SignalKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * SignalKindStandard defines a standard signal.
     */
    SignalKindStandard = 0,

    /**
     * SignalKindEnum defines a enum signal.
     */
    SignalKindEnum = 1,

    /**
     * SignalKindMultiplexer defines a multiplexer signal.
     */
    SignalKindMultiplexer = 2,
};

/**
 * SignalTypeKind represents the kind of a [SignalType].
 */
export enum SignalTypeKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * SignalTypeKindCustom defines a signal of type custom.
     */
    SignalTypeKindCustom = 0,

    /**
     * SignalTypeKindFlag defines a signal of type flag (1 bit).
     */
    SignalTypeKindFlag = 1,

    /**
     * SignalTypeKindInteger defines a signal of type integer.
     */
    SignalTypeKindInteger = 2,

    /**
     * SignalTypeKindDecimal defines a signal of type float.
     */
    SignalTypeKindDecimal = 3,
};
