name: Build and Release Application

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: canturin, platform: linux/amd64, os: ubuntu-latest},
          # {name: wailsTest, platform: windows/amd64, os: windows-latest},
          # {name: wailsTest, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}

# jobs:
#   build-and-release:
#     strategy:
#       matrix:
#         # os: [ubuntu-latest, macos-latest, windows-latest]
#          os: [ubuntu-latest]
         
#     runs-on: ${{ matrix.os }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: '1.24'

#       - name: Install wails3
#         run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

#       - name: Test
#         run: wails3 doctor
