name: Build and Release Application

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {platform: linux/amd64, os: ubuntu-latest},
          # {name: wailsTest, platform: windows/amd64, os: windows-latest},
          # {name: wailsTest, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: "Linux: Install Dependencies"
        if: runner.os == 'Linux'
        id: linux_discovery
        run: |
          sudo apt-get -yq update
          DISTRO=$(lsb_release -rs) # Get the distribution version (e.g., "22.04", "24.04")
          if [[ "$DISTRO" == "20.04" ]]; then
            sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
          elif [[ "$DISTRO" == "22.04" ]]; then
            sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
          elif [[ "$DISTRO" == "24.04" ]]; then
            sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu
          else
            echo "Unsupported Linux distribution: $DISTRO"
            exit 1 # Fail the workflow if the distribution is not supported
          fi
          echo "DISTRO=$DISTRO" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install wails3
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest
        shell: bash

      - name: "Linux: Add Perms"
        if: runner.os  == 'Linux'
        run: chmod +x build/linux/*
        shell: bash

      - name: Package Application
        run: wails3 package
        shell: bash

      - name: Print bin Folder
        run: ls -l ./bin
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{runner.os}}-package
          path: |
            ./bin/
            *\bin\*

  release:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{runner.os}}-package
          path: ./release

      - name: Print workspace
        run: ls -R ./release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "canturin ${{ github.ref_name }}"
          files: ./release/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}